/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as TemasRouteImport } from './routes/temas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasRoute = TemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/desempenho': typeof DesempenhoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/temas': typeof TemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/desempenho': typeof DesempenhoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/temas': typeof TemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/desempenho': typeof DesempenhoRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/temas': typeof TemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/comparar' | '/desempenho' | '/perfil' | '/ranking' | '/temas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparar' | '/desempenho' | '/perfil' | '/ranking' | '/temas'
  id:
    | '__root__'
    | '/'
    | '/comparar'
    | '/desempenho'
    | '/perfil'
    | '/ranking'
    | '/temas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompararRoute: typeof CompararRoute
  DesempenhoRoute: typeof DesempenhoRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  TemasRoute: typeof TemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas': {
      id: '/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof TemasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompararRoute: CompararRoute,
  DesempenhoRoute: DesempenhoRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  TemasRoute: TemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
